version: '3'
services:
  qma-microservice:
    build: 
      context: ./qma-microservice
      dockerfile: Dockerfile
    volumes: 
      - /usr/src/app/node_modules
      - ./qma-microservice:/usr/src/app
    restart: always
    environment: 
      - DB=mongodb://mongo:27017/covidhack
    command: npm start
    ports:
      - "8000:8000"
    links:
      - mongo
  mongo:
    image: mvertes/alpine-mongo
    expose:
      - 27017
    volumes: 
      - ./data:/data/db

    